quiet: true
skip_download: true
framework:
  - terraform

# Only run checks we explicitly choose (signal)
check:
  # Encryption / logging / access aligned to ISO slice above
  - CKV_AWS_18   # S3 access logging
  - CKV_AWS_21   # S3 versioning enabled
  - CKV_AWS_144  # S3 public access block
  - CKV_AWS_145  # S3 encryption enabled
  - CKV_AWS_19   # IAM policy no admin * (broad)
  - CKV_AWS_62   # CloudTrail enabled

# Everything else ignored
skip_check: []
