stages:
  - validate
  - test
  - security
  - policy-check
  - deploy
  - evidence

variables:
  TF_ROOT: "platform/devsecops/terraform/evidence_s3"

validate_terraform:
  stage: validate
  script:
    - cd $TF_ROOT
    - terraform init -backend=false
    - terraform validate

test_python:
  stage: test
  script:
    - pip install -r platform/devsecops/python/requirements-dev.txt
    - pytest || echo "pytest not yet configured, skipping"

security_scan:
  stage: security
  script:
    - echo "Run SAST / secrets scanning here (e.g., trufflehog, bandit)"
  allow_failure: true

policy_check:
  stage: policy-check
  script:
    - cd $TF_ROOT
    - terraform init -backend=false
    - terraform plan -out=tfplan
    - terraform show -json tfplan > tfplan.json
    - opa eval --format pretty --fail-defined \
        -i tfplan.json \
        -d platform/governance/policies_as_code/opa/terraform_guardrails.rego \
        "data.terraform.guardrails.dlp.deny"
  allow_failure: false

deploy:
  stage: deploy
  when: manual
  script:
    - cd $TF_ROOT
    - terraform init
    - terraform apply -auto-approve

generate_evidence:
  stage: evidence
  when: manual
  script:
    - python platform/devsecops/scripts/generate_evidence_report.py
  artifacts:
    paths:
      - evidence/
